### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by power1997** [darek-margas/iotawatt-2-chargehq#1]
keep getting this error?

Traceback (most recent call last):
  File "/home/pi/charge.py", line 15, in <module>
    my_parser.add_argument( "ip", metavar="192.168.1.110", type=str, help="IP Address of IoTaWatt", required=True )
  File "/usr/lib/python3.9/argparse.py", line 1410, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "/usr/lib/python3.9/argparse.py", line 1526, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals

**Comment by darek-margas** [comment]
How exactly you invoke script?

**Comment by power1997** [comment]
hi, using python3 on rasp pim worked out i needed to use arguments which i have:
python3 charge.py --ip 192.168.1.111 --grid MainsWatts --production Solar_Generating --key 817d7715-5c54-4ca6-b880-8f6256035ccf

seems to attempt to post, but charge HQ shows:

<img width="703" alt="Screenshot 2023-09-11 at 9 09 25 am" src="https://github.com/darek-margas/iotawatt-2-chargehq/assets/45223184/c1caddfd-853b-4f52-877b-184602d00774">

**Comment by darek-margas** [comment]
I run Python 3.6.9 so certainly different version. Need to think where to put 3.9 to test it. Try to remove ", required=True", should fix it.

**Comment by darek-margas** [comment]
Also from your error you have line:
my_parser.add_argument( "ip", metavar="192.168.1.110", type=str, help="IP Address of IoTaWatt", required=True )
While in the script it is:
my_parser.add_argument( "--ip", metavar="IP address", type=str, help="IP Address of IoTaWatt", required=True )

Without "--" it would not work giving exactly what you got. Are you sure script is alright?

**Comment by power1997** [comment]
thanks, so since that orignal post i had deleted the script and pasted purely as it appears which has gotten me close to posting correctly.
So using the posted script i get this working with no errors on the rasp pi:
pi@piaware:~ $ python3 charge.py --ip 192.168.1.110 --grid MainsWatts --production Solar_Generating --key 817d7715-5c54-4ca6-b880-8f6256035ccf
pi@piaware:~ $ 
but still showing unauthorised on chargehq

**Comment by power1997** [comment]
also remove required = true but still unautorised at charge hq end

**Comment by darek-margas** [comment]
Likely the key is wrong, also script should print feedback from chrgehq after run and this should say something about why they refuse it.

**Comment by power1997** [comment]
I hard coded the ip address for the iota watt in the script and solar adnd mains for some testing and get this response in chrome under testing:
[[-877.3,1160.1]]

added a print json in the script for testing and get this:

python3 charge.py --key 817d7715-5c55-4ca6-b880-8f6256035ccf
JSON Payload:
{"apiKey": "817d7715-5c55-4ca6-b880-8f6256035ccf", "error": "Collection error: Unauthorized"}

key is double checked correct

**Comment by power1997** [comment]
good news, so further testing I've worked out possibly a password was blocking access to the iota watt, have now allowed unrestricted access when on lan in the iotwatt and appears to have posted correctly to charge hq.

thanks for your fast responses. great working script now...
thanks
